//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by NetPlot.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_SUBTRACT_PAGE               102
#define IDP_SOCKETS_INIT_FAILED         104
#define IDD_PROCESS_PAGE                106
#define IDR_MAINFRAME                   128
#define IDR_NetPlotTYPE                 129
#define IDD_FILEDIALOG                  130
#define IDD_PARAMETERS                  131
#define IDD_COLORDLG                    132
#define IDD_LABELS                      133
#define IDR_CONTEXTMENU                 133
#define IDD_PHASE_PAGE                  134
#define IDD_REGIONS_PAGE                135
#define IDD_OFFSETDIALOG                138
#define IDD_YEXPAND_PAGE                139
#define IDC_SERVERLIST                  1000
#define IDC_DIRLIST                     1001
#define IDC_FILELIST                    1002
#define IDC_MOVEUP                      1003
#define IDC_MOVEDOWN                    1004
#define IDC_CURRENTPATH                 1005
#define IDC_REMOVE                      1006
#define IDC_REMOVEALL                   1007
#define IDC_ADDBUTTON                   1008
#define IDC_REVERSE                     1009
#define IDC_TITLE                       1010
#define IDC_SIZECX                      1011
#define IDC_SIZECY                      1012
#define IDC_LABELX                      1014
#define IDC_LABELY                      1015
#define IDC_RANGEFROM                   1016
#define IDC_RANGETO                     1017
#define IDC_GLOBALSCALING               1018
#define IDC_YEXPANSION                  1019
#define IDC_AUTOARRANGE                 1020
#define IDC_OFFSETX                     1021
#define IDC_OFFSETY                     1022
#define IDC_RANGEFULL                   1023
#define IDC_RANGEHERTZ                  1024
#define IDC_RANGEPPM                    1025
#define IDC_FROMPROMPT                  1026
#define IDC_TOPROMPT                    1027
#define IDC_LABELXPROMPT                1028
#define IDC_LABELYPROMPT                1029
#define IDC_DRIVECOMBO                  1030
#define IDC_BACKGROUNDCOLORCOMBO        1031
#define IDC_AXISCOLORCOMBO              1033
#define IDC_TITLECOLORCOMBO             1034
#define IDC_BLKONWHTBUTTON              1036
#define IDC_WHTONBLKBUTTON              1037
#define IDC_VERSIONSTATIC               1038
#define IDC_INTEGRALCOLORCOMBO          1038
#define IDC_LABELSEDIT                  1039
#define IDC_MAINCURSORCOLORCOMBO        1039
#define IDC_LABELSIZECOMBO              1040
#define IDC_ZOOMCURSORCOLORCOMBO        1040
#define IDC_AXISFONTCOMBO               1041
#define IDC_BASELINECOLORCOMBO          1041
#define IDC_LABELFONTCOMBO              1042
#define IDC_TITLEFONTCOMBO              1043
#define IDC_DCLEVELBUTTON               1044
#define IDC_TRUNCATEBUTTON              1045
#define IDC_APODIZEBUTTON               1046
#define IDC_APOSHAPECOMBO               1047
#define IDC_APOVALUECOMBO               1048
#define IDC_APOUNITCOMBO                1049
#define IDC_FTBUTTON                    1050
#define IDC_ZEROBUTTON                  1051
#define IDC_PHASEAUTOABUTTON            1053
#define IDC_PHASEAUTOABBUTTON           1054
#define IDC_MAGNITUDEBUTTON             1056
#define IDC_LABELCOMBO                  1057
#define IDC_AllCHECK                    1058
#define IDC_PHASESELECTCOMBO            1059
#define IDC_CLONEBUTTON                 1060
#define IDC_ATCURSORCHECK               1061
#define IDC_UPBUTTON                    1062
#define IDC_DOWNBUTTON                  1063
#define IDC_LEFTPHASEBUTTON             1064
#define IDC_RIGHTPHASEBUTTON            1065
#define IDC_CLONEUPBUTTON               1066
#define IDC_CLONEDOWNBUTTON             1067
#define IDC_UNDOPHASEBUTTON             1068
#define IDC_PHASEPROMPTSTATIC           1069
#define IDC_ADDREGIONBUTTON             1070
#define IDC_CLEARREGIONBUTTON           1071
#define IDC_CLEARALLREGIONBUTTON        1072
#define IDC_BASELINEORDERCOMBO          1073
#define IDC_FITINTEGRALBUTTON           1076
#define IDC_CALCULATEBASELINECHECK      1077
#define IDC_BASELINEQUITBUTTON          1078
#define IDC_OFFSETSTATIC                1079
#define IDC_ILTINTEGRALBUTTON           1079
#define IDC_OFFSETEDIT                  1080
#define IDC_SPECUPBUTTON                1081
#define IDC_SPECDOWNBUTTON              1082
#define IDC_YEXPANDSELECTCOMBO          1082
#define IDC_YEXPANDRESETBUTTON          1083
#define IDC_YEXPANDEDIT                 1084
#define IDC_YEXPANDUPDATEBUTTON         1085
#define IDC_GLOBALCHECK                 1086
#define IDC_CSPECTRUMCOMBO              1088
#define IDC_SCOLORCOMBO                 1090
#define IDC_ALLCOLORCHECK               1091
#define IDC_SUBTRACTLIST                1099
#define IDC_SUBTRACTBUTTON              1100
#define IDC_SUBTRACTCHECK               1101
#define IDC_SUBTRACTCANCELBUTTON        1102
#define IDC_SUBTRACTSLIDER              1103
#define IDC_LEFTEDIT                    1104
#define IDC_RIGHTEDIT                   1105
#define IDC_SUBTRACTSTATIC              1107
#define IDC_SUBTRACTGROUPSTATIC         1108
#define IDC_SUBTRACTFROMSTATIC          1109
#define IDC_SUBTRACTTOSTATIC            1110
#define ID_FILE_ADD                     32771
#define ID_VIEW_PORT                    32772
#define ID_VIEW_LANDSCAPE               32773
#define ID_EDIT_COLORS                  32774
#define ID_EDIT_PARAMETERS              32775
#define ID_EDIT_LABELS                  32776
#define ID_FILE_MYSAVEAS                32777
#define ID_VIEW_ZOOM                    32778
#define ID_VIEW_FULL                    32779
#define ID_INTEGRAL_ADDINTEGRAL         32780
#define ID_INTEGRAL_REMOVEINTEGRAL      32781
#define ID_INTEGRAL_CLEARALL            32782
#define ID_CONTEXT_SINGLEPOINTINTEGRAL  32783
#define ID_INTEGRAL_FITINTEGRALS        32784
#define ID_CURSOR_DIFFERENCE            32785
#define ID_INTEGRAL_ILTINTEGRALS        32785
#define ID_Y_UP                         32786
#define ID_Y_DOWN                       32787
#define ID_Y_X1                         32788
#define ID_PROCESS_PROCESS              32793
#define ID_PROCESS_PHASE                32794
#define ID_PROCESS_SUBTRACT             32795
#define ID_PROCESS_REGIONS              32796
#define ID_PROCESS_YEXPANSION           32797
#define ID_VIEW_AUTOMATIC               32798
#define ID_CONTEXT_SETOFFSETHERE        32815
#define ID_VIEW_GLOBAL                  32824
#define ID_EDIT_DATACLASS               32830
#define ID_VIEW_DATACLASS               32832

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        141
#define _APS_NEXT_COMMAND_VALUE         32834
#define _APS_NEXT_CONTROL_VALUE         1111
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
